name: CSV Scheduled Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update: 
    environment: actions
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false

    env:
      TZ: Asia/Tokyo
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rye
        uses: sksat/setup-rye@v0.12.0
      - name: Sync Rye
        run: |
          cd ./tool
          rye sync
      - name: Run Script
        run: |
          python ./tools/src/main.py
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
